# Generated by assistant: add display_name to Profile
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
    ]
