<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-09 01:13
=======
# Generated by Django 5.2.7 on 2025-11-30 17:59
>>>>>>> 0d89449ca40b8a6a691be2496f6d17c11e7ed708

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_display_name'),
        ('users', '0002_profilepicture'),
    ]

    operations = [
    ]
