# Generated by Django 5.2.7 on 2025-11-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_display_name'),
        ('users', '0002_profilepicture'),
    ]

    operations = [
    ]
