# Generated by Django 5.2.7 on 2025-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_profile_display_name_0002_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
