# Generated by Django 5.2.7 on 2025-12-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
