# Generated by Django 5.2.7 on 2025-12-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_suspended_profile_suspended_at_and_more'),
        ('users', '0006_alter_profilepicture_image'),
    ]

    operations = [
    ]
