# Generated by Django 5.2.7 on 2025-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20251209_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'Eastern Time'), ('US/Central', 'Central Time'), ('US/Mountain', 'Mountain Time'), ('US/Pacific', 'Pacific Time'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Tokyo', 'Tokyo'), ('Asia/Shanghai', 'Shanghai'), ('Australia/Sydney', 'Sydney'), ('America/Toronto', 'Toronto'), ('America/Mexico_City', 'Mexico City')], default='UTC', max_length=63),
        ),
    ]
