# Generated by Django 5.2.7 on 2025-12-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
    ]
