# Generated by Django 5.2.7 on 2025-11-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_tag_alter_post_title_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
