# Generated by Django 5.2.7 on 2025-11-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_tags_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food')], default='general', max_length=50),
        ),
    ]
