# Generated by Django 5.2.7 on 2025-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('leaderboard', 'Leaderboard')], default='general', max_length=50),
        ),
    ]
