# Generated by Django 5.2.7 on 2025-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('leaderboard', 'Leaderboard'), ('cio_leaders', 'CIO Leaders')], default='general', max_length=50),
        ),
    ]
