# Generated by Django 5.2.7 on 2025-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('cio_wide', 'CIO-Wide'), ('friends_only', 'Friends Only')], default='public', max_length=20),
        ),
    ]
