# Generated by Django 5.2.7 on 2025-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_flagged_inappropriate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged_inappropriate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
