# Generated by Django 5.2.7 on 2025-12-09 04:43

import django.db.models.deletion
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.forum_image_upload_to),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=forum.models.forum_image_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.post')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
