# Generated by Django 5.2.7 on 2025-12-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_comment_is_flagged_inappropriate_and_more'),
        ('forum', '0010_post_privacy'),
    ]

    operations = [
    ]
