# Generated by Django 5.2.7 on 2025-12-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_post_image_postimage'),
        ('forum', '0011_merge_20251209_0008'),
    ]

    operations = [
    ]
