# Generated by assistant: add image field to Task
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_proofs/'),
        ),
    ]
